### ISSUE TITLE
Consider using `dump-env`

### ISSUE THREAD

**Issue by sobolevn** [SpicyPizza/create-envfile#1]
Hi! Thanks for building this action. It is extremely useful in my workflow.

And since my workflow requires to create `.env` files inside the build I have created [`dump-env`](https://github.com/sobolevn/dump-env) sometime ago.

Its features:
1. Creates `.env` files from env vars
2. Creates `.env` files from `.env.template`
3. Allows to mix these two

It is written in `python` and fits this project perfectly. Maybe we can join our forces here? 🙂

**Comment by AngelOnFira** [comment]
Hi @sobolevn, thanks for the issue! I'm going to take a look over this in the next few days. At an initial glance, `dump-env` looks promising, so I hope that I'll be able to integrate it :100:

**Comment by AngelOnFira** [comment]
I'm going to close this as I think using a package to achieve what is needed is a bit out of scope of this simple action.
