### ISSUE TITLE
directory not working

### ISSUE THREAD

**Issue by saschati** [SpicyPizza/create-envfile#15]
I can't understand why the file I specified doesn't create a file, what am I doing wrong?

![image](https://user-images.githubusercontent.com/36109878/109847537-fc30fd00-7c57-11eb-94c3-773b90458826.png)

**Comment by grzegorzduda** [comment]
I believe this might be a duplicate of https://github.com/SpicyPizza/create-envfile/issues/9.

**Comment by AngelOnFira** [comment]
Closing as duplicate.
