### ISSUE TITLE
README non-explicit on wether _SECRET_ is optional.

### ISSUE THREAD

**Issue by HunterKohler** [SpicyPizza/create-envfile#16]
The README is non-explicit on wether _SECRET_ is optional in a variable name. 
This seems like a tiny oversight in documentation. I'm not sure how to fix it, because I don't really know wether it is optional, or the implications of not putting \_SECRET\_.

**Comment by AngelOnFira** [comment]
Are you referring to this line of the documentation?
```
envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
```
I suppose the documentation might be a bit ambiguous, as the name of the variable only matters for what you'll expect to see in your envfile. The `envkey_` prefix is only there for the Action to be able to discover the variables you want to add to the file. I suppose it might we worth adding what that example Action would output.

To be clear for now, the Action in the docs will output a file called `.env` that contains:
```
DEBUG: false
SOME_API_KEY: "123456abcdef"
SECRET_KEY: "the_secret_from_the_repository_secrets"
```
