### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Ariseaz** [SpicyPizza/create-envfile#19]
Traceback (most recent call last):
  File "/create-envfile.py", line 22, in <module>
    with open(os.path.join(path, directory, file_name), "w") as text_file:
FileNotFoundError: [Errno 2] No such file or directory: 'None/***/.env'

**Comment by davidlcarrascal** [comment]
Hi @Ariseaz, with the new version you need to put the Github action path before your directory.

` directory: /github/workspace/{{YOUR_DIRECTORY}}
`

**Comment by Ariseaz** [comment]
OK, thanks.

Will look into it.

Regards

**Comment by BrianHenryIE** [comment]
Looks like this will be in the next release, but what worked for me today was `directory: ${{ github.workspace }}`
