### ISSUE TITLE
Constant "error in your yaml syntax"

### ISSUE THREAD

**Issue by OZZlE** [SpicyPizza/create-envfile#21]
yml file:

    name: Run tests
    on:
      pull_request:
        branches: [master, develop]
    jobs:
      create-envfile:
        runs-on: ubuntu-18.04
        steps:
        - name: Make envfile
          uses: SpicyPizza/create-envfile@v1
          with:
            CONTENTFUL_MANAGEMENT_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}
            NEXT_PUBLIC_CONTENTFUL_DELIVERY_TOKEN: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_DELIVERY_TOKEN }}
            NEXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_SPACE_ID }}
            SITE_SEARCH_API_KEY: ${{ secrets.SITE_SEARCH_API_KEY }}
            NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT: master
            SITE_SEARCH_ENGINE_SLUG: test
            directory: .
            file_name: .env
          - name: Install modules
            run: yarn
          - name: Run tests
            run: yarn jest
          - name: Run Translations & Build
            run: yarn translations && yarn build

Result:

![Skärmavbild 2021-05-04 kl  15 34 33](https://user-images.githubusercontent.com/893783/117011633-4da84780-acee-11eb-8cd8-eb95c6bbdd70.png)

**Comment by OZZlE** [comment]
`- name: Install modules` should have the same indentation as `- name: Make envfile` ... my bad but still get:

Unexpected input(s) 'envkey_CONTENTFUL_MANAGEMENT_TOKEN', 'envkey_NEXT_PUBLIC_CONTENTFUL_DELIVERY_TOKEN', 'envkey_NEXT_PUBLIC_CONTENTFUL_SPACE_ID', 'envkey_SITE_SEARCH_API_KEY', 'envkey_NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT', 'envkey_SITE_SEARCH_ENGINE_SLUG', 'directory', valid inputs are ['entryPoint', 'args', 'file_name']

not sure how this is supposed to be used..

**Comment by AngelOnFira** [comment]
The error you're getting is discussed more in #10, so I'll close this issue.
