### ISSUE TITLE
Add directory support for env file

### ISSUE THREAD

**Issue by sumit4613** [SpicyPizza/create-envfile#4]
Hey @AngelOnFira, thanks for creating this github action it helps alot.

I wanted to create `.env` files in a specified directory rather than at root but this feature wasn't available, that's why I forked this repository and implemented those changes.
Please checkout this [forked version](https://github.com/sumit4613/create-envfile) and if you think that it can be merged with your repo, please let me know i'll raise a PR with the required changes.

**NOTE**: At first, I didn't thought that you'll want to add these changes that's why I have updated `README.md`. Let me know if you want to add changes, then I will revert back all changes from `README.md`.

Thanks!

**Comment by AngelOnFira** [comment]
This definitely looks like some useful functionaility! Feel free to submit a PR. Make sure it allows for maintainers to commit, as I think I'll change up how it's displayed a little. Thanks! :tada:

**Comment by sumit4613** [comment]
@AngelOnFira Have raised a PR for this. Do let me know if any change is required.

**Comment by ZarcoNontol** [comment]
Yes please! This will be a really good feature, looking forward to use it
