### ISSUE TITLE
Empty env keys aren't backwards compatible

### ISSUE THREAD

**Issue by AngelOnFira** [SpicyPizza/create-envfile#42]
Well, somehow this broke a project CI/CD pipeline I am working on. It was earlier configured to use empty Email Host Name, hence it's currently failing with the error `**Empty env key**`. Any help would be appreciated

_Originally posted by @mannyanebi in https://github.com/SpicyPizza/create-envfile/issues/40#issuecomment-1040521720_

**Comment by AngelOnFira** [comment]
So this was fixed from #29, where I agree that it would be better for CI to fail if a key is empty (it can't be found in secrets potentially). @mannyanebi it sounds like your .env file is suppose to have an empty value?

**Comment by AngelOnFira** [comment]
I will also add, if you use `SpicyPizza/create-envfile@v1.2` for the action instead of `@main`/`@v1` then it should work fine :+1:

**Comment by mannyanebi** [comment]
I think that it would be a helpful flag for backward compactibility. For the use case, even though it's not recommended to have empty values for env keys, but probably others may want to have that for test purposes or something related to that.

**Comment by mannyanebi** [comment]
https://github.com/SpicyPizza/create-envfile/issues/42#issuecomment-1040579899

I used `SpicyPizza/create-envfile@v1.2` for the action on the project, and it worked out fine. Thanks @AngelOnFira

**Comment by nickrupert7** [comment]
Just another voice here, I also ran into this issue where a pipeline on my project broke, since the change was not backwards compatible. Usually you'd consider a breaking change like this to bump the major version (ie `SpicyPizza/create-envfile@2`), but in the meantime, thank you @AngelOnFira for the quick solution!

**Comment by nickrupert7** [comment]
I'd also like to throw it out there that in order to support a forward transition to the new version, it would be nice to have a mechanism for giving undefined env keys a default value.

**Comment by AngelOnFira** [comment]
I've updated the tags for v1 and v1.3 to point to the new version, let me know if any other issues come up :)
