### ISSUE TITLE
Do not mutate key name

### ISSUE THREAD

**Issue by dpalmasan** [SpicyPizza/create-envfile#46]
Hello, I started to use this action for one use case I had. The issue is that for some keys, for example `MyValidEnvVarName` it mutates it into `MYVALIDENVVARNAME`. I am not sure if there is already a flag or something to not mutate the var name, I didn't find it on the documentation. Would be good having this. Currently my solution was updating the code, but for larger code (that do not depend on me only) it is kind of laborious and prone to errors.

Thanks in advance

**Comment by AngelOnFira** [comment]
Unfortunately, this is Github Actions that is causing this. In [these docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepswith) it describes how `first_name` becomes `INPUT_FIRST_NAME`. I don't think there would be an easy way to handle this, but if  you have any recommendation, I'm open to try something else :)
