### ISSUE TITLE
Container action is only supported on Linux

### ISSUE THREAD

**Issue by CNombres** [SpicyPizza/create-envfile#48]
Im getting this, it seems to only be working on Linux.

**Comment by mrbish** [comment]
I've faced the same issue with `runs-on: macos-latest`.
```
Warning: Unexpected input(s) 'envkey_GOOGLE_MAPS_API_KEY', valid inputs are ['entryPoint', 'args', 'file_name', 'directory', 'fail_on_empty']
...
Error: Container action is only supported on Linux
```

**Comment by FeMaffezzolli** [comment]
+1

**Comment by acortesma** [comment]
+1

**Comment by MHase** [comment]
+1

**Comment by AngelOnFira** [comment]
@CNombres @mrbish if either of you are still around, it would be helpful to see if the migration to TypeScript works out of the box, or if you run into any issues :)
