### ISSUE TITLE
Question: What does this do to an already existing .env file present in the specified directory?

### ISSUE THREAD

**Issue by malthew** [SpicyPizza/create-envfile#49]
Just want to know, what would happen if there's already an existing .env file in the specified directory present, and what to do if that would cause any conflicts?

**Comment by AngelOnFira** [comment]
The file would be overwritten:

```python
with open(full_path, "w") as text_file:
    text_file.write(out_file)
```

I suppose something could be introduced to check if a file exists first, but I went on the assumption that any existing `.env` files are likely gitignored.

**Comment by malthew** [comment]
I see, that's what I assumed as well. Just wanted to make sure since I didn't see it mentioned in the readme. Thanks for the answer and for a great action!
