### ISSUE TITLE
Sorted keys breaks variable dependence in the envfile

### ISSUE THREAD

**Issue by danielporto** [SpicyPizza/create-envfile#50]
I've observed that the keys on the generated env file are sorted. 
However it breaks some variables that uses other variables in the env file.
For instance:
suppose a variable name DOMAIN_NAME=example.com
envkey_DOMAIN_NAME: 'example.com'
followed by another one such as BAR_HOST_FQDN=bar.${DOMAIN_NAME}.
envkey_BAR_HOST_FQDN: "bar.${DOMAIN_NAME}"

the original env file is created such as
DOMAIN_NAME=example.com
BAR_HOST_FQDN=bar.${DOMAIN_NAME}

But the resulting translated env file is:
BAR_HOST_FQDN=bar.${DOMAIN_NAME}
DOMAIN_NAME=example.com

However, DOMAIN_NAME is not defined by the time BAR_HOST_FQDN is evaluated resulting in:
BAR_HOST_FQDN: bar
DOMAIN_NAME: example.com

which is different from the produced in the original env file:
BAR_HOST_FQDN: bar.example.com
DOMAIN_NAME: example.com

This doesn't seem to be much but it broke several large env files I have.

**Comment by evandrmb** [comment]
I'm also with this issue. I think it's much to be honest, since order matters at env files this issue is a no-go for many situations.

**Comment by AngelOnFira** [comment]
I'm looking into this now, I'm also not sure why I added sorting.

**Comment by AngelOnFira** [comment]
Ok so I started sorting them so I'd have reproducible tests, but I didn't consider the ramifications of needing a specific order. I'll revert that change, and add a flag in case people might want the file to be sorted. Sorry about that!

Commit: [`d81fee5` (#38)](https://github.com/SpicyPizza/create-envfile/pull/38/commits/d81fee559b95db46488b5793aa3fc82ee9dd8577)
