### ISSUE TITLE
Add option to fail step on "Unexpected input" warning

### ISSUE THREAD

**Issue by ErlanBazarov** [SpicyPizza/create-envfile#8]
Currently, step passes even if I provided incorrect key-value to "with" section. It would be good if there would be a way to fail step on incorrect key-value pair

**Comment by AngelOnFira** [comment]
Hmm, @ErlanBazarov can you give some examples? Do you mean that we should do some validation on the keys like `file_name` and `directory`?

**Comment by AngelOnFira** [comment]
Closing due to lack of information.
